### ISSUE TITLE
ama go brrrrrrrrrrrrrrrrrrrrrrrrrrrr

### ISSUE THREAD

**Issue by JBYT27** [darkdarcool/AMA#1]
1. Why did you make this?
2. What is ur fav video game?
3. What kind of program are you making currently?
4. is this question poggers?

Thanks!

**Comment by darkdarcool** [comment]
1. idk
2. probs enter and exit the gungeon(and splatoon 2)(AND HYPE FOR SPLATOON 3)
3. I making mark up stuff 
4. yea

**Comment by JBYT27** [comment]
lol, thanks!
